/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArrayUtilities */

#ifndef _Included_ArrayUtilities
#define _Included_ArrayUtilities
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArrayUtilities
 * Method:    sumOf
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_ArrayUtilities_sumOf
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     ArrayUtilities
 * Method:    squareAll
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ArrayUtilities_squareAll
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
