/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StringUtilities */

#ifndef _Included_StringUtilities
#define _Included_StringUtilities
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StringUtilities
 * Method:    getHashOf
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_StringUtilities_getHashOf
  (JNIEnv *, jclass, jstring);

/*
 * Class:     StringUtilities
 * Method:    getReverseOf
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_StringUtilities_getReverseOf
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
